# Generated by Django 4.2.5 on 2024-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_emial_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=25)),
                ('Gender', models.CharField(max_length=25)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('DOB', models.CharField(max_length=25)),
                ('SelectMembershpplan', models.CharField(max_length=200)),
                ('SelectTrainer', models.CharField(max_length=55)),
                ('Referanse', models.CharField(max_length=55)),
                ('Address', models.TextField()),
            ],
        ),
    ]
