# Generated by Django 4.2.5 on 2024-01-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_membershipplan_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='prise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
