# Generated by Django 4.2.5 on 2024-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_membershipplan_prise_alter_trainer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='prise',
            field=models.IntegerField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(max_length=25),
        ),
    ]
