# Generated by Django 4.2.5 on 2024-01-24 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Selectdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
