# Generated by Django 4.2.5 on 2024-02-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
