# Generated by Django 4.2.5 on 2024-02-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='img',
            field=models.ImageField(default='default_img.jpg', upload_to='plans'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='plandetals',
            field=models.TextField(default='Membership Plan'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.IntegerField(max_length=4),
        ),
    ]
