# Generated by Django 4.2.5 on 2024-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_remove_enrollment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='video',
            field=models.FileField(default='default_video_path', upload_to='plans/'),
        ),
    ]
