# Generated by Django 4.2.5 on 2024-02-26 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_membershipplan_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='video',
        ),
    ]
